language: android

notifications:
  email: false

sudo: false


jdk:
  - oraclejdk8


addons:
  apt:
    packages:
      - oracle-java8-installer


env:
  global:
    - BUILD_TOOLS_VERSION=23.0.3
    - COMPILE_SDK_VERSION=23


android:
  components:
    - tools

    - platform-tools

    - build-tools-$BUILD_TOOLS_VERSION

    - android-$COMPILE_SDK_VERSION

    - extra-android-m2repository

    - sys-img-$ANDROID_ABI-android-$ANDROID_TARGET_VERSION

before_script:
  - chmod +x gradlew

script:
  - ./gradlew test

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
